// Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// values_test.go tests reading back the merged Helm values a bundle installed.
//
// Area of Concern: recovering what a bundle actually deployed
// - ReadReleaseValues() - per-deployer layout, layering, and fail-closed reads
//
// The two layouts are not hypothetical: four deployers write
// <path>/values.yaml with cluster-values.yaml layered on top, and flux inlines
// the same values under spec.values in its HelmRelease.

package bundleinfo_test

import (
	"context"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	stderrors "errors"

	"github.com/NVIDIA/aicr/pkg/bundler/bundleinfo"
	"github.com/NVIDIA/aicr/pkg/defaults"
	"github.com/NVIDIA/aicr/pkg/errors"
	"github.com/NVIDIA/aicr/pkg/header"
)

// valuesBundle writes a minimal but valid bundle-info.yaml naming the given
// releases, so each case exercises Read's own validation rather than routing
// around it.
func valuesBundle(t *testing.T, releases []bundleinfo.Release) string {
	t.Helper()
	return valuesBundleWith(t, releases, false)
}

func valuesBundleWith(t *testing.T, releases []bundleinfo.Release, vendored bool) string {
	t.Helper()
	dir := t.TempDir()
	info := &bundleinfo.BundleInfo{
		APIVersion: header.StableGroupVersion,
		Kind:       string(header.KindBundleInfo),
		Build: bundleinfo.Build{
			Deployer: "helm",
			Recipe: bundleinfo.Recipe{
				Path:   "recipe.yaml",
				Digest: "sha256:3b1f8c2ad9e7546102bb8f4c7d0e9a1358cc4f6b2e8d70a94f1c5b3e6d820947",
			},
			Settings: bundleinfo.Settings{VendorCharts: vendored},
		},
		Layout: bundleinfo.Layout{Entrypoint: "deploy.sh", Releases: releases},
	}
	if _, err := bundleinfo.Write(context.Background(), dir, info); err != nil {
		t.Fatalf("Write() failed: %v", err)
	}
	return dir
}

// plant writes content at dir/rel, creating parents.
func plant(t *testing.T, dir, rel, content string) {
	t.Helper()
	path := filepath.Join(dir, rel)
	if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
		t.Fatalf("MkdirAll(%s) failed: %v", filepath.Dir(path), err)
	}
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		t.Fatalf("WriteFile(%s) failed: %v", path, err)
	}
}

func TestReadReleaseValues(t *testing.T) {
	tests := []struct {
		name     string
		releases []bundleinfo.Release
		files    map[string]string
		want     map[string]map[string]any
	}{
		{
			name: "values.yaml alone",
			releases: []bundleinfo.Release{
				{Name: "nodewright-operator", Component: "nodewright-operator", Path: "005-nodewright-operator"},
			},
			files: map[string]string{
				"005-nodewright-operator/values.yaml": "fullnameOverride: skyhook-operator\n",
			},
			want: map[string]map[string]any{
				"nodewright-operator": {"fullnameOverride": "skyhook-operator"},
			},
		},
		{
			name: "cluster-values.yaml layers over values.yaml",
			releases: []bundleinfo.Release{
				{Name: "c", Component: "c", Path: "001-c"},
			},
			files: map[string]string{
				"001-c/values.yaml":         "fullnameOverride: from-values\nkeep: true\n",
				"001-c/cluster-values.yaml": "fullnameOverride: from-cluster\n",
			},
			want: map[string]map[string]any{
				"c": {"fullnameOverride": "from-cluster", "keep": true},
			},
		},
		{
			name: "an empty cluster-values.yaml changes nothing",
			releases: []bundleinfo.Release{
				{Name: "c", Component: "c", Path: "001-c"},
			},
			files: map[string]string{
				"001-c/values.yaml":         "fullnameOverride: kept\n",
				"001-c/cluster-values.yaml": "# Generated by AICR\n---\n",
			},
			want: map[string]map[string]any{"c": {"fullnameOverride": "kept"}},
		},
		{
			name: "cluster-values.yaml deep-merges rather than replacing",
			releases: []bundleinfo.Release{
				{Name: "c", Component: "c", Path: "001-c"},
			},
			files: map[string]string{
				"001-c/values.yaml":         "grafana:\n  fullnameOverride: g\n  other: keep\n",
				"001-c/cluster-values.yaml": "grafana:\n  fullnameOverride: g2\n",
			},
			want: map[string]map[string]any{
				"c": {"grafana": map[string]any{"fullnameOverride": "g2", "other": "keep"}},
			},
		},
		{
			name: "flux reads spec.values from the recorded manifest",
			releases: []bundleinfo.Release{
				{
					Name:      "nodewright-operator",
					Component: "nodewright-operator",
					Path:      "nodewright-operator",
					Manifest:  "nodewright-operator/helmrelease.yaml",
				},
			},
			files: map[string]string{
				"nodewright-operator/helmrelease.yaml": "apiVersion: helm.toolkit.fluxcd.io/v2\n" +
					"kind: HelmRelease\n" +
					"metadata:\n  name: nodewright-operator\n" +
					"spec:\n  values:\n    fullnameOverride: skyhook-operator\n",
			},
			want: map[string]map[string]any{
				"nodewright-operator": {"fullnameOverride": "skyhook-operator"},
			},
		},
		{
			name: "values.yaml wins over a manifest that also carries values",
			releases: []bundleinfo.Release{
				{Name: "c", Component: "c", Path: "001-c", Manifest: "001-c/application.yaml"},
			},
			files: map[string]string{
				"001-c/values.yaml": "fullnameOverride: from-values-file\n",
				"001-c/application.yaml": "apiVersion: argoproj.io/v1alpha1\nkind: Application\n" +
					"spec:\n  values:\n    fullnameOverride: should-not-win\n",
			},
			want: map[string]map[string]any{"c": {"fullnameOverride": "from-values-file"}},
		},
		{
			name: "a manifest-only component yields no values and is not an error",
			releases: []bundleinfo.Release{
				{Name: "rdma", Component: "rdma", Path: "001-rdma"},
			},
			files: map[string]string{"001-rdma/manifests/cr.yaml": "kind: NodeWright\n"},
			want:  map[string]map[string]any{},
		},
		{
			// Present with an empty map, not absent: the manifest exists and
			// declares no values, which is a statement that the release pinned
			// none. See TestReadReleaseValuesKeepsAReleaseThatPinnedNothing.
			name: "a manifest without spec.values states an empty set",
			releases: []bundleinfo.Release{
				{Name: "c", Component: "c", Path: "001-c", Manifest: "001-c/helmrelease.yaml"},
			},
			files: map[string]string{
				"001-c/helmrelease.yaml": "apiVersion: helm.toolkit.fluxcd.io/v2\nkind: HelmRelease\n" +
					"spec:\n  chart:\n    spec:\n      chart: nodewright\n",
			},
			want: map[string]map[string]any{"c": {}},
		},
		{
			name:     "a bundle with no releases yields nothing",
			releases: nil,
			files:    nil,
			want:     map[string]map[string]any{},
		},
		{
			name: "releases are keyed by component, not by release name",
			releases: []bundleinfo.Release{
				{Name: "aicr-stack-c", Component: "c", Path: "001-c"},
			},
			files: map[string]string{"001-c/values.yaml": "fullnameOverride: x\n"},
			want:  map[string]map[string]any{"c": {"fullnameOverride": "x"}},
		},
		{
			// An injected wrapper carries its PARENT in Component, so counting
			// its values would attribute them to a chart that never saw them —
			// and here it would beat the real release to the key, since -pre
			// lands at the earlier wave.
			name: "an injected -pre release does not shadow its component",
			releases: []bundleinfo.Release{
				{Name: "c-pre", Component: "c", Path: "001-c-pre"},
				{Name: "c", Component: "c", Path: "002-c"},
			},
			files: map[string]string{
				"001-c-pre/values.yaml": "fullnameOverride: wrapper\n",
				"002-c/values.yaml":     "fullnameOverride: real\n",
			},
			want: map[string]map[string]any{"c": {"fullnameOverride": "real"}},
		},
		{
			name: "a component whose own name ends in a reserved suffix is kept",
			releases: []bundleinfo.Release{
				{Name: "thing-post", Component: "thing-post", Path: "001-thing-post"},
			},
			files: map[string]string{"001-thing-post/values.yaml": "fullnameOverride: kept\n"},
			want:  map[string]map[string]any{"thing-post": {"fullnameOverride": "kept"}},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			dir := valuesBundle(t, tt.releases)
			for rel, content := range tt.files {
				plant(t, dir, rel, content)
			}
			got, err := bundleinfo.ReadReleaseValues(context.Background(), dir)
			if err != nil {
				t.Fatalf("ReadReleaseValues() failed: %v", err)
			}
			if !reflect.DeepEqual(got, tt.want) {
				t.Errorf("ReadReleaseValues() = %#v, want %#v", got, tt.want)
			}
		})
	}
}

// TestReadReleaseValuesPropagatesMissingBundleInfo keeps the pre-stamping
// bundle a real state a caller can branch on, rather than an empty result that
// reads as "this bundle pinned no object names".
func TestReadReleaseValuesPropagatesMissingBundleInfo(t *testing.T) {
	_, err := bundleinfo.ReadReleaseValues(context.Background(), t.TempDir())
	if err == nil {
		t.Fatal("want an error for a directory with no bundle-info.yaml, got nil")
	}
	if !stderrors.Is(err, errors.New(errors.ErrCodeNotFound, "")) {
		t.Errorf("want ErrCodeNotFound, got %v", err)
	}
}

// TestReadReleaseValuesRefusesSymlink mirrors Read's own O_NOFOLLOW guard: an
// untrusted bundle arrives from an OCI registry or a GitOps clone and must not
// redirect this read at anything outside itself.
func TestReadReleaseValuesRefusesSymlink(t *testing.T) {
	dir := valuesBundle(t, []bundleinfo.Release{
		{Name: "c", Component: "c", Path: "001-c"},
	})
	outside := filepath.Join(t.TempDir(), "elsewhere.yaml")
	if err := os.WriteFile(outside, []byte("fullnameOverride: leaked\n"), 0o600); err != nil {
		t.Fatalf("WriteFile() failed: %v", err)
	}
	if err := os.MkdirAll(filepath.Join(dir, "001-c"), 0o750); err != nil {
		t.Fatalf("MkdirAll() failed: %v", err)
	}
	if err := os.Symlink(outside, filepath.Join(dir, "001-c", "values.yaml")); err != nil {
		t.Fatalf("Symlink() failed: %v", err)
	}

	_, err := bundleinfo.ReadReleaseValues(context.Background(), dir)
	if err == nil {
		t.Fatal("want a symlinked values.yaml refused, got nil")
	}
	if !strings.Contains(err.Error(), "symlink") {
		t.Errorf("want the error to name the symlink, got %v", err)
	}
}

// TestReadReleaseValuesRejectsOversizeValues bounds the read the same way
// Read bounds its own: a values file is attacker-influenced input.
func TestReadReleaseValuesRejectsOversizeValues(t *testing.T) {
	dir := valuesBundle(t, []bundleinfo.Release{
		{Name: "c", Component: "c", Path: "001-c"},
	})
	plant(t, dir, "001-c/values.yaml",
		"key: "+strings.Repeat("x", int(defaults.MaxBundleValuesBytes))+"\n")

	_, err := bundleinfo.ReadReleaseValues(context.Background(), dir)
	if err == nil {
		t.Fatal("want an oversize values.yaml rejected, got nil")
	}
	if !stderrors.Is(err, errors.New(errors.ErrCodeInvalidRequest, "")) {
		t.Errorf("want ErrCodeInvalidRequest, got %v", err)
	}
}

// A --vendor-charts bundle nests its values one level under the vendored
// chart's name, because that is the only way Helm forwards a wrapper's values
// to a subchart. Read verbatim, every object-name path would be one level too
// deep, so a comparison against a resolved recipe would report the real name
// as dropped and a phantom nested one as added — and --inherit-from would act
// on that by nulling out the name it exists to preserve.
func TestReadReleaseValuesUnnestsVendoredCharts(t *testing.T) {
	const wrapperChart = "apiVersion: v2\nname: gpu-operator\nversion: 0.1.0\n" +
		"dependencies:\n  - name: gpu-operator\n    version: v25.3.4\n    repository: \"\"\n"

	tests := []struct {
		name     string
		vendored bool
		files    map[string]string
		want     map[string]any
	}{
		{
			name:     "a vendored release is read at the subchart's depth",
			vendored: true,
			files: map[string]string{
				"001-c/Chart.yaml":  wrapperChart,
				"001-c/values.yaml": "gpu-operator:\n  fullnameOverride: gpu-operator\n",
			},
			want: map[string]any{"fullnameOverride": "gpu-operator"},
		},
		{
			// The chart name is not always the component name, so the key is
			// taken from the wrapper's dependency rather than guessed.
			name:     "the subchart key comes from the wrapper dependency",
			vendored: true,
			files: map[string]string{
				"001-c/Chart.yaml": "apiVersion: v2\nname: c\nversion: 0.1.0\n" +
					"dependencies:\n  - name: not-the-component-name\n    version: v1\n    repository: \"\"\n",
				"001-c/values.yaml": "not-the-component-name:\n  fullnameOverride: real\n",
			},
			want: map[string]any{"fullnameOverride": "real"},
		},
		{
			name:     "cluster-values layers before the un-nesting",
			vendored: true,
			files: map[string]string{
				"001-c/Chart.yaml":  wrapperChart,
				"001-c/values.yaml": "gpu-operator:\n  fullnameOverride: from-values\n",
				"001-c/cluster-values.yaml": "gpu-operator:\n" +
					"  fullnameOverride: from-cluster\n",
			},
			want: map[string]any{"fullnameOverride": "from-cluster"},
		},
		{
			// An injected local-helm folder carries no dependency, so there is
			// nothing nested and its values must be left alone.
			name:     "a wrapper with no dependency is left flat",
			vendored: true,
			files: map[string]string{
				"001-c/Chart.yaml":  "apiVersion: v2\nname: c\nversion: 0.1.0\n",
				"001-c/values.yaml": "fullnameOverride: flat\n",
			},
			want: map[string]any{"fullnameOverride": "flat"},
		},
		{
			name:     "a non-vendored bundle is never un-nested",
			vendored: false,
			files: map[string]string{
				"001-c/Chart.yaml":  wrapperChart,
				"001-c/values.yaml": "gpu-operator:\n  fullnameOverride: gpu-operator\n",
			},
			want: map[string]any{"gpu-operator": map[string]any{"fullnameOverride": "gpu-operator"}},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			dir := valuesBundleWith(t, []bundleinfo.Release{
				{Name: "c", Component: "c", Path: "001-c"},
			}, tt.vendored)
			for rel, content := range tt.files {
				plant(t, dir, rel, content)
			}
			got, err := bundleinfo.ReadReleaseValues(context.Background(), dir)
			if err != nil {
				t.Fatalf("ReadReleaseValues() failed: %v", err)
			}
			if !reflect.DeepEqual(got["c"], tt.want) {
				t.Errorf("values = %#v, want %#v", got["c"], tt.want)
			}
		})
	}
}

// A component whose values file is comments-only (grove ships one) states an
// empty map, which is a fact: it deployed and pinned nothing. Dropping it
// would tell inheritance this is a first deploy, so a name a later release
// adds would apply instead of being held back — while upgrade-check, reading
// the same two artifacts, would report the rename. The two halves must agree.
func TestReadReleaseValuesKeepsAReleaseThatPinnedNothing(t *testing.T) {
	tests := []struct {
		name      string
		release   bundleinfo.Release
		files     map[string]string
		wantEntry bool
	}{
		{
			name:      "a comments-only values file is an empty statement, not an absence",
			release:   bundleinfo.Release{Name: "c", Component: "c", Path: "001-c"},
			files:     map[string]string{"001-c/values.yaml": "# Generated by AICR\n---\n"},
			wantEntry: true,
		},
		{
			name:    "a manifest declaring no values is also a statement",
			release: bundleinfo.Release{Name: "c", Component: "c", Path: "001-c", Manifest: "001-c/hr.yaml"},
			files: map[string]string{
				"001-c/hr.yaml": "apiVersion: helm.toolkit.fluxcd.io/v2\nkind: HelmRelease\nspec:\n  chart: {}\n",
			},
			wantEntry: true,
		},
		{
			name:      "a manifest-only component with neither states nothing",
			release:   bundleinfo.Release{Name: "c", Component: "c", Path: "001-c"},
			files:     map[string]string{"001-c/manifests/cr.yaml": "kind: NodeWright\n"},
			wantEntry: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			dir := valuesBundle(t, []bundleinfo.Release{tt.release})
			for rel, content := range tt.files {
				plant(t, dir, rel, content)
			}
			got, err := bundleinfo.ReadReleaseValues(context.Background(), dir)
			if err != nil {
				t.Fatalf("ReadReleaseValues() failed: %v", err)
			}
			values, present := got["c"]
			if present != tt.wantEntry {
				t.Fatalf("entry present = %v, want %v (values %#v)", present, tt.wantEntry, values)
			}
			if tt.wantEntry && len(values) != 0 {
				t.Errorf("values = %#v, want an empty map", values)
			}
		})
	}
}

// TestReadReleaseValuesRejectsMalformedYAML keeps a values file that does not
// parse an error rather than an empty projection. Silently reading no object
// names out of an unreadable file would report that a component pins none,
// which is the false "nothing moved" this axis exists to remove.
func TestReadReleaseValuesRejectsMalformedYAML(t *testing.T) {
	tests := []struct {
		name     string
		releases []bundleinfo.Release
		files    map[string]string
	}{
		{
			name:     "values.yaml",
			releases: []bundleinfo.Release{{Name: "c", Component: "c", Path: "001-c"}},
			files:    map[string]string{"001-c/values.yaml": "fullnameOverride: [unclosed\n"},
		},
		{
			name:     "cluster-values.yaml",
			releases: []bundleinfo.Release{{Name: "c", Component: "c", Path: "001-c"}},
			files: map[string]string{
				"001-c/values.yaml":         "fullnameOverride: fine\n",
				"001-c/cluster-values.yaml": "\tthis: is not yaml\n",
			},
		},
		{
			name: "flux manifest",
			releases: []bundleinfo.Release{
				{Name: "c", Component: "c", Path: "001-c", Manifest: "001-c/helmrelease.yaml"},
			},
			files: map[string]string{"001-c/helmrelease.yaml": "spec:\n  values: [unclosed\n"},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			dir := valuesBundle(t, tt.releases)
			for rel, content := range tt.files {
				plant(t, dir, rel, content)
			}
			_, err := bundleinfo.ReadReleaseValues(context.Background(), dir)
			if err == nil {
				t.Fatal("want malformed YAML rejected, got nil")
			}
			if !stderrors.Is(err, errors.New(errors.ErrCodeInvalidRequest, "")) {
				t.Errorf("want ErrCodeInvalidRequest, got %v", err)
			}
		})
	}
}

// TestReadReleaseValuesRejectsIrregularFile mirrors Read's regular-file check.
// A directory (or a device) where a values file belongs is a malformed bundle,
// not an absent values file.
func TestReadReleaseValuesRejectsIrregularFile(t *testing.T) {
	dir := valuesBundle(t, []bundleinfo.Release{{Name: "c", Component: "c", Path: "001-c"}})
	if err := os.MkdirAll(filepath.Join(dir, "001-c", "values.yaml"), 0o750); err != nil {
		t.Fatalf("setup: mkdir: %v", err)
	}
	_, err := bundleinfo.ReadReleaseValues(context.Background(), dir)
	if err == nil {
		t.Fatal("want a directory in place of values.yaml rejected, got nil")
	}
	if !strings.Contains(err.Error(), "regular file") {
		t.Errorf("want the error to name the regular-file check, got %v", err)
	}
}

// TestReadReleaseValuesLayersLikeHelm pins the two coalescing rules a second
// -f file follows, which is what install.sh does with cluster-values.yaml:
// an explicit null removes a key, and a non-map replaces whatever it lands on.
func TestReadReleaseValuesLayersLikeHelm(t *testing.T) {
	tests := []struct {
		name    string
		values  string
		cluster string
		want    map[string]any
	}{
		{
			name:    "an explicit null removes the key",
			values:  "fullnameOverride: gone\nkept: yes\n",
			cluster: "fullnameOverride: null\n",
			want:    map[string]any{"kept": "yes"},
		},
		{
			name:    "a map replaces a scalar",
			values:  "a: scalar\n",
			cluster: "a:\n  fullnameOverride: nested\n",
			want:    map[string]any{"a": map[string]any{"fullnameOverride": "nested"}},
		},
		{
			name:    "a scalar replaces a map",
			values:  "a:\n  fullnameOverride: nested\n",
			cluster: "a: scalar\n",
			want:    map[string]any{"a": "scalar"},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			dir := valuesBundle(t, []bundleinfo.Release{{Name: "c", Component: "c", Path: "001-c"}})
			plant(t, dir, "001-c/values.yaml", tt.values)
			plant(t, dir, "001-c/cluster-values.yaml", tt.cluster)

			got, err := bundleinfo.ReadReleaseValues(context.Background(), dir)
			if err != nil {
				t.Fatalf("ReadReleaseValues() failed: %v", err)
			}
			if !reflect.DeepEqual(got["c"], tt.want) {
				t.Errorf("values = %#v, want %#v", got["c"], tt.want)
			}
		})
	}
}

// TestReadReleaseValuesHonorsContext proves the per-release loop checks
// cancellation, per the repo rule for long-running iteration.
func TestReadReleaseValuesHonorsContext(t *testing.T) {
	dir := valuesBundle(t, []bundleinfo.Release{
		{Name: "c", Component: "c", Path: "001-c"},
	})
	plant(t, dir, "001-c/values.yaml", "fullnameOverride: x\n")

	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	if _, err := bundleinfo.ReadReleaseValues(ctx, dir); err == nil {
		t.Fatal("want a canceled context to fail the read, got nil")
	}
}
